db:
  entities:
    - address:
        count: 100
    - house:
        count: 100
    - job:
        count: 500
    - person:
        count: 300
    - owner:
        count: 100
    - neighbor:
        count: 100